# This file is managed by FlowCrafter. Manual changes will be overwritten
# the next time you run FlowCrafter.
---
library:
  github:
    owner: otterbuild
    repository: workflows
workflows:
  - name: json
    jobs:
      - style
  - name: markdown
    jobs:
      - lint
      - style
  - name: yaml
    jobs:
      - lint
      - style
